<?php
// $Id: $

function eml_config_form_menu () {
  $items = array();
  $items['quiz'] = array (
    'title' => t('Create an EML config file'),
    'page callback' => 'quiz_page', 
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
    );
    return $items;
}

function quiz_page () {
  return drupal_get_form('quiz_form');
}         

function person_subform ($form) {
  $states = array(
    'AK' => t('Alaska'),
    'AL' => t('Alabama'),
    'AR' => t('Arkansas'),
    'AZ' => t('Arizona'),
    'CA' => t('California'),
    'CO' => t('Colorado'),
    'CT' => t('Connecticut'),
    'DC' => t('District Of Columbia'),
    'DE' => t('Delaware'),
    'FL' => t('Florida'),
    'GA' => t('Georgia'),
    'HI' => t('Hawaii'),
    'IA' => t('Iowa'),
    'ID' => t('Idaho'),
    'IL' => t('Illinois'),
    'IN' => t('Indiana'),
    'KS' => t('Kansas'),
    'KY' => t('Kentucky'),
    'LA' => t('Louisiana'),
    'MA' => t('Massachusetts'),
    'MD' => t('Maryland'),
    'ME' => t('Maine'),
    'MI' => t('Michigan'),
    'MN' => t('Minnesota'),
    'MO' => t('Missouri'),
    'MS' => t('Mississippi'),
    'MT' => t('Montana'),
    'NC' => t('North Carolina'),
    'ND' => t('North Dakota'),
    'NE' => t('Nebraska'),
    'NH' => t('New Hampshire'),
    'NJ' => t('New Jersey'),
    'NM' => t('New Mexico'),
    'NV' => t('Nevada'),
    'NY' => t('New York'),
    'OH' => t('Ohio'),
    'OK' => t('Oklahoma'),
    'OR' => t('Oregon'),
    'PA' => t('Pennsylvania'),
    'PR' => t('Puerto Rico'),
    'RI' => t('Rhode Island'),
    'SC' => t('South Carolina'),
    'SD' => t('South Dakota'),
    'TN' => t('Tennessee'),
    'TX' => t('Texas'),
    'UT' => t('Utah'),
    'VA' => t('Virginia'),
    'VT' => t('Vermont'),
    'WA' => t('Washington'),
    'WI' => t('Wisconsin'),
    'WV' => t('West Virginia'),
    'WY' => t('Wyoming'),  
  );
  
 $country = array (
   'United States' => t('United States'),
   'Abkhazia' => t('Abkhazia'),
   'Afghanistan' => t('Afghanistan'),
   'Akrotiri and Dhekelia' => t('Akrotiri and Dhekelia'),
   'Åland' => t('Åland'),
   'Albania' => t('Albania'),
   'Algeria' => t('Algeria'),
   'American Samoa' => t('American Samoa'),
   'Andorra' => t('Andorra'),
   'Angola' => t('Angola'),
   'Anguilla' => t('Anguilla'),
   'Antigua and Barbuda' => t('Antigua and Barbuda'),
   'Argentina' => t('Argentina'),
   'Armenia' => t('Armenia'),
   'Aruba' => t('Aruba'),
   'Ascension Island' => t('Ascension Island'),
   'Australia' => t('Australia'),
   'Austria' => t('Austria'),
   'Azerbaijan' => t('Azerbaijan'),
   'Bahamas, The' => t('Bahamas, The'),
   'Bahrain' => t('Bahrain'),
   'Bangladesh' => t('Bangladesh'),
   'Barbados' => t('Barbados'),
   'Belarus' => t('Belarus'),
   'Belgium' => t('Belgium'),
   'Belize' => t('Belize'),
   'Benin' => t('Benin'),
   'Bermuda' => t('Bermuda'),
   'Bhutan' => t('Bhutan'),
   'Bolivia' => t('Bolivia'),
   'Bosnia' => t('Bosnia'),
   'Botswana' => t('Botswana'),
   'Brazil' => t('Brazil'),
   'Brunei' => t('Brunei'),
   'Bulgaria' => t('Bulgaria'),
   'Burkina Faso' => t('Burkina Faso'),
   'Burundi' => t('Burundi'),
   'Cambodia' => t('Cambodia'),
   'Cameroon' => t('Cameroon'),
   'Canada' => t('Canada'),
   'Cape Verde' => t('Cape Verde'),
   'Cayman Islands' => t('Cayman Islands'),
   'Central African Republic' => t('Central African Republic'),
   'Chad' => t('Chad'),
   'Chile' => t('Chile'),
   'China' => t('China'),
   'Christmas Island' => t('Christmas Island'),
   'Cocos (Keeling) Islands' => t('Cocos (Keeling) Islands'),
   'Colombia' => t('Colombia'),
   'Comoros' => t('Comoros'),
   'Congo (República)' => t('Congo (República)'),
   'Congo (República Democrática)' => t('Congo (República Democrática)'),
   'Cook Islands' => t('Cook Islands'),
   'Costa Rica' => t('Costa Rica'),
   'Côte d\'Ivoire' => t('Côte d\'Ivoire'),
   'Croatia' => t('Croatia'),
   'Cuba' => t('Cuba'),
   'Cyprus' => t('Cyprus'),
   'Czech Republic' => t('Czech Republic'),
   'Denmark' => t('Denmark'),
   'Djibouti' => t('Djibouti'),
   'Dominica' => t('Dominica'),
   'Dominican Republic' => t('Dominican Republic'),
   'East Timor' => t('East Timor'),
   'Ecuador' => t('Ecuador'),
   'Egypt' => t('Egypt'),
   'El Salvador' => t('El Salvador'),
   'Equatorial Guinea' => t('Equatorial Guinea'),
   'Eritrea' => t('Eritrea'),
   'Estonia' => t('Estonia'),
   'Ethiopia' => t('Ethiopia'),
   'Falkland Islands' => t('Falkland Islands'),
   'Faroe Islands' => t('Faroe Islands'),
   'Fiji' => t('Fiji'),
   'Finland' => t('Finland'),
   'France' => t('France'),
   'French Polynesia' => t('French Polynesia'),
   'Gabon' => t('Gabon'),
   'Gambia, The' => t('Gambia, The'),
   'Georgia' => t('Georgia'),
   'Germany' => t('Germany'),
   'Ghana' => t('Ghana'),
   'Gibraltar' => t('Gibraltar'),
   'Greece' => t('Greece'),
   'Greenland' => t('Greenland'),
   'Grenada' => t('Grenada'),
   'Guam' => t('Guam'),
   'Guatemala' => t('Guatemala'),
   'Guernsey' => t('Guernsey'),
   'Guinea' => t('Guinea'),
   'Guinea-Bissau' => t('Guinea-Bissau'),
   'Guyana' => t('Guyana'),
   'Haiti' => t('Haiti'),
   'Honduras' => t('Honduras'),
   'Hong Kong' => t('Hong Kong'),
   'Hungary' => t('Hungary'),
   'Iceland' => t('Iceland'),
   'India' => t('India'),
   'Indonesia' => t('Indonesia'),
   'Iran' => t('Iran'),
   'Iraq' => t('Iraq'),
   'Ireland' => t('Ireland'),
   'Isle of Man' => t('Isle of Man'),
   'Israel' => t('Israel'),
   'Italy' => t('Italy'),
   'Jamaica' => t('Jamaica'),
   'Japan' => t('Japan'),
   'Jersey' => t('Jersey'),
   'Jordan' => t('Jordan'),
   'Kazakhstan' => t('Kazakhstan'),
   'Kenya' => t('Kenya'),
   'Kiribati' => t('Kiribati'),
   'Korea, North' => t('Korea, North'),
   'Korea, South' => t('Korea, South'),
   'Kosovo' => t('Kosovo'),
   'Kuwait' => t('Kuwait'),
   'Kyrgyzstan' => t('Kyrgyzstan'),
   'Laos' => t('Laos'),
   'Latvia' => t('Latvia'),
   'Lebanon' => t('Lebanon'),
   'Lesotho' => t('Lesotho'),
   'Liberia' => t('Liberia'),
   'Libya' => t('Libya'),
   'Liechtenstein' => t('Liechtenstein'),
   'Lithuania' => t('Lithuania'),
   'Luxembourg' => t('Luxembourg'),
   'Macau' => t('Macau'),
   'Macedonia' => t('Macedonia'),
   'Madagascar' => t('Madagascar'),
   'Malawi' => t('Malawi'),
   'Malaysia' => t('Malaysia'),
   'Maldives' => t('Maldives'),
   'Mali' => t('Mali'),
   'Malta' => t('Malta'),
   'Marshall Islands' => t('Marshall Islands'),
   'Mauritania' => t('Mauritania'),
   'Mauritius' => t('Mauritius'),
   'Mayotte' => t('Mayotte'),
   'Mexico' => t('Mexico'),
   'Micronesia' => t('Micronesia'),
   'Moldova' => t('Moldova'),
   'Monaco' => t('Monaco'),
   'Mongolia' => t('Mongolia'),
   'Montenegro' => t('Montenegro'),
   'Montserrat' => t('Montserrat'),
   'Morocco' => t('Morocco'),
   'Mozambique' => t('Mozambique'),
   'Myanmar (Burma)' => t('Myanmar (Burma)'),
   'Nagorno-Karabakh' => t('Nagorno-Karabakh'),
   'Namibia' => t('Namibia'),
   'Nauru' => t('Nauru'),
   'Nepal' => t('Nepal'),
   'Netherlands' => t('Netherlands'),
   'Netherlands Antilles' => t('Netherlands Antilles'),
   'New Caledonia' => t('New Caledonia'),
   'New Zealand' => t('New Zealand'),
   'Nicaragua' => t('Nicaragua'),
   'Niger' => t('Niger'),
   'Nigeria' => t('Nigeria'),
   'Niue' => t('Niue'),
   'Norfolk Island' => t('Norfolk Island'),
   'Northern Cyprus' => t('Northern Cyprus'),
   'Northern Mariana Islands' => t('Northern Mariana Islands'),
   'Norway' => t('Norway'),
   'Oman' => t('Oman'),
   'Pakistan' => t('Pakistan'),
   'Palau' => t('Palau'),
   'Palestine' => t('Palestine'),
   'Panama' => t('Panama'),
   'Papua New Guinea' => t('Papua New Guinea'),
   'Paraguay' => t('Paraguay'),
   'Peru' => t('Peru'),
   'Philippines' => t('Philippines'),
   'Pitcairn Islands' => t('Pitcairn Islands'),
   'Poland' => t('Poland'),
   'Portugal' => t('Portugal'),
   'Puerto Rico' => t('Puerto Rico'),
   'Qatar' => t('Qatar'),
   'Romania' => t('Romania'),
   'Russia' => t('Russia'),
   'Rwanda' => t('Rwanda'),
   'Saint Barthélemy' => t('Saint Barthélemy'),
   'Saint Helena' => t('Saint Helena'),
   'Saint Kitts and Nevis' => t('Saint Kitts and Nevis'),
   'Saint Lucia' => t('Saint Lucia'),
   'Saint Martin' => t('Saint Martin'),
   'Saint Pierre and Miquelon' => t('Saint Pierre and Miquelon'),
   'Saint Vincent and the Grenadines' => t('Saint Vincent and the Grenadines'),
   'Samoa' => t('Samoa'),
   'San Marino' => t('San Marino'),
   'São Tomé and Príncipe São' => t('São Tomé and Príncipe São'),
   'Saudi Arabia' => t('Saudi Arabia'),
   'Senegal' => t('Senegal'),
   'Serbia' => t('Serbia'),
   'Seychelles' => t('Seychelles'),
   'Sierra Leone' => t('Sierra Leone'),
   'Singapore' => t('Singapore'),
   'Slovakia' => t('Slovakia'),
   'Slovenia' => t('Slovenia'),
   'Solomon Islands' => t('Solomon Islands'),
   'Somalia' => t('Somalia'),
   'Somaliland' => t('Somaliland'),
   'South Africa' => t('South Africa'),
   'South Ossetia' => t('South Ossetia'),
   'Spain' => t('Spain'),
   'Sri Lanka' => t('Sri Lanka'),
   'Sudan' => t('Sudan'),
   'Suriname' => t('Suriname'),
   'Svalbard' => t('Svalbard'),
   'Swaziland' => t('Swaziland'),
   'Sweden' => t('Sweden'),
   'Switzerland' => t('Switzerland'),
   'Syria' => t('Syria'),
   'Taiwan' => t('Taiwan'),
   'Tajikistan' => t('Tajikistan'),
   'Tanzania' => t('Tanzania'),
   'Thailand' => t('Thailand'),
   'Togo' => t('Togo'),
   'Tokelau' => t('Tokelau'),
   'Tonga' => t('Tonga'),
   'Transnistria' => t('Transnistria'),
   'Trinidad and Tobago' => t('Trinidad and Tobago'),
   'Tristan da Cunha' => t('Tristan da Cunha'),
   'Tunisia' => t('Tunisia'),
   'Turkey' => t('Turkey'),
   'Turkmenistan' => t('Turkmenistan'),
   'Turks and Caicos Islands' => t('Turks and Caicos Islands'),
   'Tuvalu' => t('Tuvalu'),
   'Uganda' => t('Uganda'),
   'Ukraine' => t('Ukraine'),
   'United Arab Emirates' => t('United Arab Emirates'),
   'United Kingdom' => t('United Kingdom'),
   'United States of America' => t('United States of America'),
   'Uruguay' => t('Uruguay'),
   'Uzbekistan' => t('Uzbekistan'),
   'Vanuatu' => t('Vanuatu'),
   'Vatican City' => t('Vatican City'),
   'Venezuela' => t('Venezuela'),
   'Vietnam' => t('Vietnam'),
   'Virgin Islands, British' => t('Virgin Islands, British'),
   'Virgin Islands, United States' => t('Virgin Islands, United States'),
   'Wallis and Futuna' => t('Wallis and Futuna'),
   'Western Sahara' => t('Western Sahara'),
   'Yemen' => t('Yemen'),
   'Zambia' => t('Zambia'),
   'Zimbabwe' => t('Zimbabwe'),  
 ); 
    
  $form['persons'] = array(
    '#type' => 'fieldset',
    '#title' => t('persons'),
    '#tree' => TRUE,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );                        

  // $form['persons'] = array(
  //   '#type' => 'fieldset',
  //   '#title' => t('persons'),
  //   '#tree' => TRUE,
  //   '#collapsible' => TRUE,
  //   '#collapsed' => FALSE,
  // );                        

    
  $form['persons']['first_name'] = array (
    '#type'  => 'textfield',
    '#title' => t('first_name'),  
    '#required'  => TRUE,
    '#size'  => 15,
    '#maxlength' => 64,
    '#default_value' => variable_get('first_name', ''),    
  );

  $form['persons']['last_name'] = array (
    '#type'  => 'textfield',
    '#title' => t('last_name'),  
    '#required'  => TRUE,
    '#size'  => 60,
    '#maxlength' => 60,
    '#default_value' => variable_get('last_name', ''),
    );

  $form['persons']['organization'] = array (
    '#type'  => 'textfield',
    '#title' => t('organization'),  
    '#size'  => 60,
    '#maxlength' => 60,
    );

  $form['persons']['address'] = array (
    '#type'  => 'textfield',
    '#title' => t('address'),  
    '#size'  => 60,
    '#maxlength' => 100,
    );

  $form['persons']['city'] = array (
    '#type'  => 'textfield',
    '#title' => t('city'),  
    '#size'  => 60,
    '#maxlength' => 60,
    );

  $form['persons']['state'] = array(
    '#type' => 'select',
    '#title' => t('state'),
    '#options' => $states,
  );

  $form['persons']['zipcode'] = array (
    '#type'  => 'textfield',
    '#title' => t('zipcode'),  
    '#size'  => 60,
    '#maxlength' => 60,
    );

  $form['persons']['country'] = array(
    '#type' => 'select',
    '#title' => t('country'),
    '#options' => $country,
  );

  $form['persons']['phone'] = array (
    '#type'  => 'textfield',
    '#title' => t('phone'),  
    '#size'  => 60,
    '#maxlength' => 60,
    );

  $form['persons']['fax'] = array (
    '#type'  => 'textfield',
    '#title' => t('fax'),  
    '#size'  => 60,
    '#maxlength' => 60,
    );

  $form['persons']['role'] = array (
    '#type'     => 'select',
    '#title'    => t('role'),
    '#required'  => TRUE,
    '#options'  => array(
      'metadataProvider' => t('Metadata Provider'),
      'publisher'        => t('Publisher'),
    ),
    '#default_value' => variable_get('role', 'Metadata Provider'),
  );

  $form['persons']['email'] = array (
    '#type'  => 'textfield',
    '#title' => t('email'),  
    '#required'  => TRUE,
    '#size'  => 60,
    '#maxlength' => 60,
    '#default_value' => variable_get('email', ''),
    );

  $form['persons']['personid'] = array (
    '#type'  => 'textfield',
    '#title' => t('personid'),  
    '#size'  => 60,
    '#maxlength' => 60,
    );

  return $form;  
}

function quiz_form ($form_state) {
  $form = array();                    
  
  $form['acr'] = array(
    '#type'  => 'textfield',
    '#title' => t('Site name acronim'),  
    '#required'  => TRUE,
    '#size'  => 3,
    '#maxlength' => 3,
    '#default_value' => variable_get('acr', 'pie'),
    // '#description' => t('Site name acronim'),
  );

  $form['language'] = array(
    '#type'  => 'textfield',
    '#title' => t('Language'),  
    '#required'  => TRUE,
    '#size'  => 15,
    '#maxlength' => 64,
    '#default_value' => variable_get('language', 'english'),
  );
                                                
  $form['intellectual_rights'] = array(
    '#type' => 'textarea',
    '#title' => t('Intellectual Rights'),  
    '#default_value' =>  variable_get('intellectual_rights', ''),
    '#cols' => 60,
    '#rows' => 5,
  );

  $form['data_policies'] = array(
    '#type' => 'textarea',
    '#title' => t('Data Policies'),  
    '#default_value' =>  variable_get('data_policies', ''),
    '#cols' => 60,
    '#rows' => 5,
  );                                               
                 
  $form = person_subform($form);

  // $form['persons']['role'] = array('#type' => 'value', '#value' => 'Metadata Provider');

  // $form_state['redirect'] = array('page1', 'id=' . $form_state['values']['index_search']);
  
  $form['submit'] = array (
    '#type' => 'submit',
    '#value' => t('Create'),
    );
  
  return $form;
  
}

function quiz_form_validate ($form_id, &$form_state) {          
  // $toast = $form_state['values']['toast'];
  // 
  // if (!$toast) {
  //   form_set_error('toast error', t('You must like toast!'));
  // }
}               

function person_node_create ($organization, $address, $city, $state, $zipcode, $country, $phone, $fax, $role, $email, $personid) {  

  // $q = db_query('SELECT nid FROM node WHERE type="person" ;');
  // while ($nid = db_result($q)) {
  //   $n = node_load($nid);
  //   $n->title = $n->field_person_first_name[0]['value']." ".$n->field_person_last_name[0]['value'];
  //   $node = node_submit($n);
  //   node_save($node);
  // }
  
  $node = new StdClass();    
  $node->type = "person";
  $node->field_person_title = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_first_name = Array (0 => Array ('value' => ''));
  $node->field_person_last_name = Array (0 => Array ('value' => ''));
  $node->field_person_organization = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_address = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_city = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_state = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_zipcode = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_country = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_phone = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_fax = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_role = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_email = Array (0 => Array ('value' => 'Aaaa'));
  $node->field_person_personid = Array (0 => Array ('value' => 'Aaaa'));
  // node_submit($node); // This step is needed only in Drupal 5, not in Drupal 6.
  // node_save($node);
}             

// function config_node_create () {}

function quiz_form_submit ($form_id, &$form_state) {          
  $acr = $form_state['values']['acr'];
  $language = $form_state['values']['language'];    
  $role = $form_state['values']['persons']['role'];
                                                              
  $output = t('Hi ');
  $output .= $acr;
  $output .= t(' toast = ');
  $output .= $role;
  drupal_set_message($output);      
  
  person_node_create ($organization, $address, $city, $state, $zipcode, $country, $phone, $fax, $role, $email, $personid);
                                           
  // write_config_eml_file ();
  // $myFile = "/Library/Webserver/Documents/drupal6-local/sites/all/files/testFile.php";
  // $fh = fopen($myFile, 'w') or die("can't open file");         
  // // fwrite($fh, '
  // //   <?php
  // //   /* 
  // //    * Here goes an site specific information
  // //    */
  // // 
  // //     // TODO: hardcode the pubPlace, specific for every given site
  // //     // example: <pubPLace> Plum Island Ecosystems LTER </pubPlace>
  // //     // for now taking automatically: variable_get('site_name', NULL);
  // // 
  // //     // package_id is scope.identifier.version
  // //     // for LTER, scope is "knb-lter-ACR" where ACR is the three leter site acronym
  // //     // Non-lTER sites may not have a convention for the scope
  // //     // Identifier is a unique identifier -- usually from the "data set ID".
  // //     // Version is the $ver_id, a composites of Drupal VIDs for the related NIDs.
  // // ');
  // fwrite($fh, "<?php\n");
  // fwrite($fh, "\$acr = '$acr';\n");
  // fwrite($fh, "// \$id = content_type_data_set.content_field_dataset_id ;\n");
  // fwrite($fh, "\$scope = 'knb-lter-'.\$acr;\n");
  // fwrite($fh, "\$package_id = \$acr . '.' . \$id . '.' . \$ver_vid;\n");
  // fwrite($fh, "\$language = '$language';\n");
  // 
  // fwrite($fh, "\$role = '$role';\n");
  // fclose($fh);             
  
  db_query("INSERT INTO {content_type_config_eml_test} (field_acronim_value, field_language_value) VALUES ('%s', '%s')", $form_state['values']['acr'], $form_state['values']['language']);
  drupal_set_message(t('Your form has been saved.'));
  
}

// content_type_config_eml_test table
//  