$view = new view;
$view->name = 'harvest_list';
$view->description = 'harvest_list';
$view->tag = '';
$view->view_php = '';
$view->base_table = 'node';
$view->is_cacheable = FALSE;
$view->api_version = 2;
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
$handler = $view->new_display('default', 'Defaults', 'default');
$handler->override_option('fields', array(
  'field_dataset_station_acronym_value' => array(
    'label' => 'scope',
    'alter' => array(
      'alter_text' => 1,
      'text' => 'knb-lter-[field_dataset_station_acronym_value]',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'custom',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_dataset_station_acronym_value',
    'table' => 'node_data_field_dataset_station_acronym',
    'field' => 'field_dataset_station_acronym_value',
    'relationship' => 'none',
  ),
  'field_dataset_id_value' => array(
    'label' => 'identifier',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'custom',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_dataset_id_value',
    'table' => 'node_data_field_dataset_id',
    'field' => 'field_dataset_id_value',
    'relationship' => 'none',
  ),
  'field_dataset_ext_assoc_ref_nid' => array(
    'label' => 'Associated Researcher',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_ext_assoc_ref_nid',
    'table' => 'node_data_field_dataset_ext_assoc_ref',
    'field' => 'field_dataset_ext_assoc_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_contact_ref_nid' => array(
    'label' => 'Contact',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_contact_ref_nid',
    'table' => 'node_data_field_dataset_contact_ref',
    'field' => 'field_dataset_contact_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_datafile_ref_nid' => array(
    'label' => 'Data File Structure',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_datafile_ref_nid',
    'table' => 'node_data_field_dataset_datafile_ref',
    'field' => 'field_dataset_datafile_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_datamanager_ref_nid' => array(
    'label' => 'Data Manager',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_datamanager_ref_nid',
    'table' => 'node_data_field_dataset_datamanager_ref',
    'field' => 'field_dataset_datamanager_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_fieldcrew_ref_nid' => array(
    'label' => 'Field Crew',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_fieldcrew_ref_nid',
    'table' => 'node_data_field_dataset_fieldcrew_ref',
    'field' => 'field_dataset_fieldcrew_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_labcrew_ref_nid' => array(
    'label' => 'Lab Crew',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_labcrew_ref_nid',
    'table' => 'node_data_field_dataset_labcrew_ref',
    'field' => 'field_dataset_labcrew_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_owner_ref_nid' => array(
    'label' => 'Owner',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_owner_ref_nid',
    'table' => 'node_data_field_dataset_owner_ref',
    'field' => 'field_dataset_owner_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_biblio_ref_nid' => array(
    'label' => 'Related Bibliography',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_biblio_ref_nid',
    'table' => 'node_data_field_dataset_biblio_ref',
    'field' => 'field_dataset_biblio_ref_nid',
    'relationship' => 'none',
  ),
  'field_dataset_site_ref_nid' => array(
    'label' => 'Site',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 1,
    'id' => 'field_dataset_site_ref_nid',
    'table' => 'node_data_field_dataset_site_ref',
    'field' => 'field_dataset_site_ref_nid',
    'relationship' => 'none',
  ),
  'phpcode_3' => array(
    'label' => 'revision',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'value' => '<?php
 unset($vid_sum);   
 unset($ref_node);
 unset($node);
 unset($vid);  
 unset($file_node);
 unset($var_nids);
 unset($file_sites_nids);

 $vid_sum += $data -> node_vid;

 $ref_names = array(
   node_data_field_dataset_ext_assoc_ref_field_dataset_ext_assoc_ref_nid,
   node_data_field_dataset_contact_ref_field_dataset_contact_ref_nid,
   node_data_field_dataset_datafile_ref_field_dataset_datafile_ref_nid,
   node_data_field_dataset_datamanager_ref_field_dataset_datamanager_ref_nid,
   node_data_field_dataset_fieldcrew_ref_field_dataset_fieldcrew_ref_nid,
   node_data_field_dataset_labcrew_ref_field_dataset_labcrew_ref_nid,
   node_data_field_dataset_owner_ref_field_dataset_owner_ref_nid,
   node_data_field_dataset_biblio_ref_field_dataset_biblio_ref_nid,
   node_data_field_dataset_site_ref_field_dataset_site_ref_nid,
 );

 foreach ($ref_names as $ref_name) {      
   $ref_node = $data -> $ref_name;
   foreach ($ref_node as $inner_arr) {
     foreach ($inner_arr as $ref_nid) {
       $node = node_load($ref_nid);
       $vid  = $node -> vid;
       $vid_sum += $vid;                
     }
   }
 }                                                              
 
 foreach ($data -> node_data_field_dataset_datafile_ref_field_dataset_datafile_ref_nid as $file_nids) {
   foreach ($file_nids as $file_nid) {
     $file_node       = node_load($file_nid);
     $var_nids        = $file_node -> field_datafile_variable_ref;
     $file_sites_nids = $file_node -> field_datafile_site_ref; 
     if ($var_nids) {
       foreach ($var_nids as $var_inner) {
         foreach ($var_inner as $var_nid) {  
           $vid_sum += $var_nid;
         }
       }
     }
     if ($file_sites_nids) {
       foreach ($file_sites_nids as $file_site_inner) {
         foreach ($file_site_inner as $file_site_nid) {
           $vid_sum += $file_site_nid;    
         }
       }
     }
   }
 }
   

 print $vid_sum;
?>',
    'exclude' => 0,
    'id' => 'phpcode_3',
    'table' => 'customfield',
    'field' => 'phpcode',
    'relationship' => 'none',
  ),
  'phpcode_1' => array(
    'label' => 'documentType',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'value' => 'eml://ecoinformatics.org/eml-2.0.1',
    'exclude' => 0,
    'id' => 'phpcode_1',
    'table' => 'customfield',
    'field' => 'phpcode',
    'relationship' => 'none',
  ),
  'phpcode_2' => array(
    'label' => 'documentURL',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'value' => 'http://inigo.lternet.edu/prototype/eml_view1/<?php print($data->nid); ?>',
    'exclude' => 0,
    'id' => 'phpcode_2',
    'table' => 'customfield',
    'field' => 'phpcode',
    'relationship' => 'none',
  ),
));
$handler->override_option('filters', array(
  'type' => array(
    'operator' => 'in',
    'value' => array(
      'data_set' => 'data_set',
    ),
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'type',
    'table' => 'node',
    'field' => 'type',
    'relationship' => 'none',
  ),
));
$handler->override_option('access', array(
  'type' => 'none',
));
$handler->override_option('cache', array(
  'type' => 'none',
));
$handler->override_option('distinct', 1);
$handler->override_option('style_plugin', 'views_xml_style');
$handler->override_option('style_options', array(
  'schema' => 'raw',
  'root_element' => 'harvestList',
  'top_child_object' => 'document',
  'field_output' => 'normal',
  'plaintext_output' => 0,
  'element_output' => 'nested',
  'escape_as_CDATA' => 'no',
  'header' => '',
  'content_type' => 'text/xml',
  'author' => 'anna',
  'using_views_api_mode' => 0,
));
$handler = $view->new_display('page', 'Page', 'page_1');
$handler->override_option('path', 'harvestList_test.xml');
$handler->override_option('menu', array(
  'type' => 'none',
  'title' => '',
  'description' => '',
  'weight' => 0,
  'name' => 'navigation',
));
$handler->override_option('tab_options', array(
  'type' => 'none',
  'title' => '',
  'description' => '',
  'weight' => 0,
  'name' => 'navigation',
));
