<?php
// $Id: csv2drupal.module, v 2.0 2010-11-22 ashipunova $
/*
 * Form for eml settings, required by views_bonus_eml_export
 * ?q=csv2drupal
*/

function csv2drupal_menu() {
  
  $items = array();
  $items['csv2drupal'] = array (
    'title' => t('Export CSV files into predefined custom content types for the LTER project'),
    'page callback' => 'csv2drupal_page',
    'access arguments' => array('administer nodes'),
    'type' => MENU_SUGGESTED_ITEM,
//    'file' => 'csv2drupal_form.inc',
    );
  return $items;
}

function csv2drupal_page() {
//  $file = "/Users/ashipunova/work/drupal/lter/new/today/dataset.csv";

  $file = "/Users/ashipunova/work/drupal/lter/new/today/variable_h.csv";
  dpr("HERE URRA!");
  $content = csv_to_array($file);
  dpr($content);
}

//TODO add file name as a parametr, get throgh form or from predifined folder
//function getdataset() {
//  $file = "/Users/ashipunova/work/drupal/lter/new/today/dataset.csv";
//  if (($handle = fopen($file, "r")) === FALSE) return;
//  while (($cols = fgetcsv($handle, 1000, ",")) !== FALSE) {
//    print("\$cols\n");
//    dpr($cols);
////      foreach( $cols as $key => $val ) {
//        $dataset_array += $cols;
////      }
////      echo print_r($cols, 1);
//  }
//  if (($handle = fopen($file, "r")) !== FALSE) {
//      while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
//          $num = count($data);
////          echo "<p> $num fields in line $row: <br /></p>\n";
//          $row++;
//          for ($c = 0; $c < $num; $c++) {
////              echo $data[$c] . "<br />\n";
//              $dataset_array += $data;
//          }
//      }
//      fclose($handle);
//  }
//      return $dataset_array;
//}

//works great with title in row
  function csv_to_array($filename='', $delimiter=',')
{
    if(!file_exists($filename) || !is_readable($filename))
        return FALSE;

    $header = NULL;
    $data = array();
    if (($handle = fopen($filename, 'r')) !== FALSE)
    {
        while (($row = fgetcsv($handle, 1000, $delimiter)) !== FALSE)
        {
            if(!$header)
                $header = $row;
            else
                $data[] = array_combine($header, $row);
        }
        fclose($handle);
    }
    return $data;
}

