<?php
// $Id: csv2drupal.module, v 2.0 2010-11-22 ashipunova $
/*
 * Form for eml settings, required by views_bonus_eml_export
 * ?q=csv2drupal
*/

function csv2drupal_menu() {
  
  $items = array();
  $items['csv2drupal'] = array (
    'title' => t('Export CSV files into predefined custom content types for the LTER project'),
    'page callback' => 'csv2drupal_page',
    'access arguments' => array('administer nodes'),
    'type' => MENU_SUGGESTED_ITEM,
//    'file' => 'csv2drupal_form.inc',
    );
  return $items;
}

function csv2drupal_page() {

  global $user;
  $uid = $user->uid;

//  home
//  $file = "/Users/ashipunova/work/drupal/lter/new/today/dataset.csv";

  $file = "/Users/anna/work/drupal/lter/new/today/variable_h.csv";
  create_variable_node($file, $uid);

//  $file = "/Users/anna/work/drupal/lter/new/today/csv_examples/1982_2000gs81tusbm_DataSet.csv";
//  create_datafile_node($file);

  $file = "/Users/anna/work/drupal/lter/new/today/csv_examples_hor/1982_2000gs81tusbm_DataSet.csv";
  create_dataset_node($file, $uid);

//  $file = "/Users/anna/work/drupal/lter/new/today/csv_examples/1982_2000gs81tusbm_DataSet.csv";
//  create_person_node($file);
//
//  $file = "/Users/anna/work/drupal/lter/new/today/csv_examples/1982_2000gs81tusbm_DataSet.csv";
//  create_site_node($file);
//
//  $file = "/Users/anna/work/drupal/lter/new/today/csv_examples/1982_2000gs81tusbm_DataSet.csv";
//  create_keywords_node($file);
  
//  dpr("HERE URRA!");
//  dpr($content_a);

  

//Name
//Label
//Definition
//Missing Values
//unit
//Maximum Value
//Minimum Value
//precision
//Date Format
//Code-Definition
//Associated Data Files

//    $node = new stdClass();
//    $node->is_new = 1;
//    $node->title = ;
//    $node->body = "";
//    $node->type = "book";
//    $node->uid = 1;
//    $node->teaser = "";
//    $node->filter = 1;
//    $node->status = 1;
//    $node->comment = 2;
//    $node->created = time();
//    $node->changed = time();
//    $node->field_publisher[0]['value']='Gutenberg';
//    $node->field_author[0]['value']='Gutenberg';
//    $now = microtime(true);
//    node_save($node);
//
//
//field_attribute_label_value
//field_var_definition_value
//field_attribute_unit_value
//field_attribute_maximum_value
//field_attribute_minimum_value
//field_attribute_precision_value
//field_attribute_formatstring_value



    $q = db_query('SELECT nid FROM node WHERE type="data_set" LIMIT 1;');

  while ($nid = db_result($q)) {
    $n = node_load($nid);
//    dpr("data_set node = ");
//    dpr($n);
//    $n->title = $n->field_person_first_name[0]['value']." ".$n->field_person_last_name[0]['value'];
//    $node = node_submit($n);
//    node_save($node);

//    var_dump
  }

}

//TODO add file name as a parametr, get throgh form or from predifined folder
//function getdataset() {
//  $file = "/Users/ashipunova/work/drupal/lter/new/today/dataset.csv";
//  if (($handle = fopen($file, "r")) === FALSE) return;
//  while (($cols = fgetcsv($handle, 1000, ",")) !== FALSE) {
//    print("\$cols\n");
//    dpr($cols);
////      foreach( $cols as $key => $val ) {
//        $dataset_array += $cols;
////      }
////      echo print_r($cols, 1);
//  }
//  if (($handle = fopen($file, "r")) !== FALSE) {
//      while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
//          $num = count($data);
////          echo "<p> $num fields in line $row: <br /></p>\n";
//          $row++;
//          for ($c = 0; $c < $num; $c++) {
////              echo $data[$c] . "<br />\n";
//              $dataset_array += $data;
//          }
//      }
//      fclose($handle);
//  }
//      return $dataset_array;
//}

//works great with title in row
  function csv_to_array($filename='', $delimiter=',')
{
    if(!file_exists($filename) || !is_readable($filename)) {
        return FALSE;
    }

    $header = NULL;
    $data = array();
    if (($handle = fopen($filename, 'r')) !== FALSE)
    {
        while (($row = fgetcsv($handle, 1000, $delimiter)) !== FALSE)
        {
//          dpr($row);
            if(!$header) {
                $header = $row;
                chop_field_names($header);
            }
            else {
                $data[] = array_combine($header, $row);
            }
        }
        fclose($handle);
    }
    return $data;
}

function chop_field_names(&$header) {
  foreach ($header as $key => $value) {
    $header[$key] = rtrim($value, " ");
  }
  return $header;
}

//function person_node_create($person_settings) {
//
//  global $user;
//
//  $uid = $user->uid;
//  $node = new StdClass();
//  $node->type = "person";
//  $node->uid = $uid;
//  $node->field_person_organization = Array (0 => Array ('value' => $person_settings['organization']));
//  $node->field_person_address = Array (0 => Array ('value' => $person_settings['address']));
//  $node->field_person_city = Array (0 => Array ('value' => $person_settings['city']));
//  $node->field_person_state = Array (0 => Array ('value' => $person_settings['state']));
//  $node->field_person_zipcode = Array (0 => Array ('value' => $person_settings['zipcode']));
//  $node->field_person_country = Array (0 => Array ('value' => $person_settings['country']));
//  $node->field_person_phone = Array (0 => Array ('value' => $person_settings['phone']));
//  $node->field_person_fax = Array (0 => Array ('value' => $person_settings['fax']));
//  $node->field_person_role = Array (0 => Array ('value' => $person_settings['role']));
//  $node->field_person_email = Array (0 => Array ('email' => $person_settings['email']));
//
//  // Commented fields are here in case we will need them
//  // $node->field_person_title = Array (0 => Array ('value' => ''));
//  // $node->field_person_first_name = Array (0 => Array ('value' => ''));
//  // $node->field_person_last_name = Array (0 => Array ('value' => ''));
//  // $node->field_person_personid = Array (0 => Array ('value' => $personid));
//
//  node_save($node);
//
//  return $node->nid;
//}

function create_variable_node($file, $uid) {
  $content = csv_to_array($file);

  foreach ($content as $value) {
      $node = new StdClass();
      $node->type = "variable";
      $node->uid = $uid;
//        $node->is_new = 1;
      $node->title = $value['Name'];
      $node->field_attribute_label[0]['value'] = $value['Label'];
      $node->field_var_definition[0]['value'] = $value['Definition'];
      $node->field_var_missingvalues[0]['value'] = $value['Missing Values'];
      $node->field_attribute_unit[0]['value'] = $value['unit'];
      $node->field_attribute_maximum[0]['value'] = $value['Maximum Value'];
      $node->field_attribute_minimum[0]['value'] = $value['Minimum Value'];
      $node->field_attribute_precision[0]['value'] = $value['precision'];
      $node->field_attribute_formatstring[0]['value'] = $value['Date Format'];
      $node->field_code_definition[0]['value'] = $value['Code-Definition'];
      $node->field_attribute_assoc_datafile[0]['value'] = $value['Associated Data Files'];
//      dpr($node);
//      dpr('NEW\n');
  }
}

function create_dataset_node($file, $uid) {
  $content = csv_to_array($file);
//  dpr($content);

  foreach ($content as $value) {
//    dpr('HERE = ');
//    dpr($value['Associated Researcher']);

//    collect multiple values
    $ext_assoc[] = $value['Associated Researcher'];
  }

//taking person id
  foreach ($ext_assoc as $key => $value) {
    $q = db_query('SELECT nid FROM node WHERE type="person" and title = %d;', $value);
    while ($nid = db_result($q)) {
      dpr($value);
      dpr($nid);

    }
  }

//  $sql = "SELECT nid FROM node WHERE type = 'person' and title = '%s'";
//  $q = db_query($sql, "Laoreet Nulla Hos Saluto Minim Si Gilvus");
////
//  while ($nid = db_result($q)) {
//    $n = node_load($nid);
//    dpr($nid);
////    dpr("data_set node = ");
////    dpr($n);
////    $n->title = $n->field_person_first_name[0]['value']." ".$n->field_person_last_name[0]['value'];
////    $node = node_submit($n);
////    node_save($node);
//
////    var_dump
//  }

//      [field_dataset_datafile_ref] => Array
//        (
//            [0] => Array
//                (
//                    [nid] => 2788
//                )
//
//            [1] => Array
//                (
//                    [nid] => 2784
//                )
//
//        )

//  Array
//(
//    [0] => Terry Chapin
//    [1] => Jim Laundre
//    [2] => Donie Bret-Harte
//    [3] => Michelle Mack
//)

//  beg_end_date
//dataset_abstract
//dataset_add_info
//dataset_biblio_ref
//dataset_contact_ref
//dataset_datafile_ref
//dataset_datamanager_ref
//dataset_ext_assoc_ref
//dataset_fieldcrew_ref
//dataset_id
//dataset_labcrew_ref
//dataset_maintenance
//dataset_owner_ref
//dataset_publication_date
//dataset_purpose
//dataset_related_links
//dataset_short_name
//dataset_site_ref
//instrumentation
//methods
//quality


      $node = new StdClass();
      $node->type = "data_set";
      $node->uid = $uid;
//        $node->is_new = 1;
      $node->title = $value['Title'];
      $node->field_beg_end_date[0]['value']             = $value['Date Range'];
      $node->field_dataset_abstract[0]['value']         = $value['Abstract'];
      $node->field_dataset_add_info[0]['value']         = $value['Additional Information'];
//      $node->field_dataset_biblio_ref[0]['value']       = $value['Related Bibliography'];
//      $node->field_dataset_contact_ref[0]['value']      = $value['Contact'];
//      $node->field_dataset_datafile_ref[0]['value']     = $value['Data File Structure'];
//      $node->field_dataset_datamanager_ref[0]['value']  = $value['Data Manager'];
      $node->field_dataset_ext_assoc_ref[0]['value']    = $value['Associated Researcher'];
//      $node->field_dataset_fieldcrew_ref[0]['value']    = $value['Field Crew'];
      $node->field_dataset_id[0]['value']               = $value['Dataset ID'];
//      $node->field_dataset_labcrew_ref[0]['value']      = $value['Lab Crew'];
      $node->field_dataset_maintenance[0]['value']      = $value['Maintenance'];
//      $node->field_dataset_owner_ref[0]['value']        = $value['Owner'];
      $node->field_dataset_publication_date[0]['value'] = $value['Publication Date'];
      $node->field_dataset_purpose[0]['value']          = $value['Purpose'];
      $node->field_dataset_related_links[0]['value']    = $value['Related Links'];
      $node->field_dataset_short_name[0]['value']       = $value['Short Name'];
//      $node->field_dataset_site_ref[0]['value']         = $value['Site'];
      $node->field_instrumentation[0]['value']          = $value['Instrumentation'];
      $node->field_methods[0]['value']                  = $value['Methods'];
      $node->field_quality[0]['value']                  = $value['Quality Assurance'];
//      dpr($node);
//      dpr('NEW\n');

  
}
